"""Timestamp for concurrency

Revision ID: 17e9fa2874c0
Revises: 5edee166e1aa
Create Date: 2025-12-30 14:33:36.322594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e9fa2874c0'
down_revision: Union[str, Sequence[str], None] = '5edee166e1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('retries', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('enqueued_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'enqueued_at')
    op.drop_column('videos', 'retries')
    # ### end Alembic commands ###
