"""Video Schema updated

Revision ID: 5edee166e1aa
Revises: a5da56f97901
Create Date: 2025-12-30 13:57:18.134324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5edee166e1aa'
down_revision: Union[str, Sequence[str], None] = 'a5da56f97901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_to_videos_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_name', sa.String(length=100), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_to_videos')
    op.add_column('videos', sa.Column('processing', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('enqueued', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'enqueued')
    op.drop_column('videos', 'processing')
    op.create_table('user_to_videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_to_videos_user_id_fkey')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], name=op.f('user_to_videos_video_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_to_videos_pkey'))
    )
    op.drop_table('user_to_videos_session')
    # ### end Alembic commands ###
