"""Video Schema updated

Revision ID: a5da56f97901
Revises: 77ffc6d9a957
Create Date: 2025-12-30 13:16:42.242535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5da56f97901'
down_revision: Union[str, Sequence[str], None] = '77ffc6d9a957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('ready', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'ready')
    # ### end Alembic commands ###
